// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Game struct {
	Id          int64
	Uuid        string
	GridSize    int64
	MinesAmount int64
	GameFailed  bool
	GameWon     bool
	GridState   string
	CreatedAt   sql.NullTime
}

type Move struct {
	Id       int64
	GameId   int64
	MoveType string
	Row      int64
	Col      int64
	CreateAt sql.NullTime
}
